[package]
name = "automatafl-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
automatafl-logic = { path = "../logic" }

uuid = { version = "1", features = ["serde", "v4"] }

serde = { version = "1.0", features = ["derive"] }

axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }

tracing = "0.1"
tracing-subscriber = "0.3"