[package]
name = "automatafl-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
automatafl-logic = { path = "../logic" }

uuid = { version = "1", features = ["serde", "v4"] }
bcrypt = "0.17"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

futures = "0.3"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["cors"] }

tracing = "0.1"
tracing-subscriber = "0.3"